# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
bash = {}
bootstrap = {}
ca-certificates = {}
coreutils = {}
drivers = {}
escalated = {}
extrautils = {}
findutils = {}
initfs = {}
gcc = {}
gnu-binutils = {}
ipcd = {}
kernel = {}
netdb = {}
netstack = {}
netutils = {}
pkgutils = {}
ptyd = {}
redoxerd = {}
relibc = {}
uutils = {}

# User settings
[users.root]
password = ""
uid = 0
gid = 0
name = "root"
home = "/root"

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
pcid /etc/pcid.d/
escalated
"""

[[files]]
path = "/etc/init.d/10_net"
data = """
smolnetd
dnsd
dhcpd
"""

[[files]]
path = "/etc/init.d/20_redoxer"
data = """
echo
echo ## running redoxer-env ##
sh /etc/redoxer-env
"""

[[files]]
path = "/etc/redoxer-env"
data = """
#!/bin/sh

echo
echo ## preparing environment ##
export GROUPS=0
export HOME=file:/root
export HOST=redox
export SHELL=file:/bin/sh
export UID=0
export USER=root
cd file:/root
env

echo
echo ## running redoxer ##
exec redoxerd
"""

[[files]]
path = "/etc/net/dns"
data = """
208.67.222.222
"""

[[files]]
path = "/etc/net/ip"
data = """
10.0.2.15
"""

[[files]]
path = "/etc/net/ip_router"
data = """
10.0.2.2
"""

[[files]]
path = "/etc/net/ip_subnet"
data = """
255.255.255.0
"""

[[files]]
path = "/etc/net/mac"
data = """
54-52-00-ab-cd-ef
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"

[[files]]
path = "/etc/group"
data = """
root;0;root
"""

[[files]]
path = "/etc/hostname"
data = """
redox
"""

[[files]]
path = "/usr/bin"
data = "../bin"
symlink = true

[[files]]
path = "/usr/games"
data = "../games"
symlink = true

[[files]]
path = "/usr/include"
data = "../include"
symlink = true

[[files]]
path = "/usr/lib"
data = "../lib"
symlink = true

[[files]]
path = "/usr/share"
data = "../share"
symlink = true

[[files]]
path = "/tmp"
data = ""
directory= true
# 0o1777
mode = 1023

[[files]]
path = "/dev/null"
data = "null:"
symlink = true

[[files]]
path = "/dev/random"
data = "rand:"
symlink = true

[[files]]
path = "/dev/urandom"
data = "rand:"
symlink = true

[[files]]
path = "/dev/zero"
data = "zero:"
symlink = true
